version: '3'

services:
 nginx:
    image: 'nginx:1.19'
    env_file:
      - config.env
    restart: unless-stopped
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime
      - drive:/usr/share/nginx/html/Drive
      - media:/usr/share/nginx/html/Media
      - ${WEBROOT}:/usr/share/nginx/html
      - ./nginxconf/htpasswd:/etc/nginx/htpasswd
      - ./nginxconf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginxconf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginxconf/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./nginxconf/autoindex.xslt:/etc/nginx/autoindex.xslt
      - ./nginxconf/autoindex_gallery.xslt:/etc/nginx/autoindex_gallery.xslt
      - /etc/letsencrypt/archive/${DOMAIN_NAME}/privkey1.pem:/etc/letsencrypt/privkey.pem
      - /etc/letsencrypt/archive/${DOMAIN_NAME}/fullchain1.pem:/etc/letsencrypt/fullchain.pem
    depends_on:
       - php
       - mysql
       - jobber
    networks:
      space-net:
        ipv4_address: 172.28.1.2
        aliases:
          - nginx_net

 php:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-php
    image: 'updownio_php:latest'
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${WEBROOT}:/var/www/html
    networks:
      space-net:
        ipv4_address: 172.28.1.3
        aliases:
          - php_net
 
 mysql:
    image: hypriot/rpi-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=updownio
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mysqldata:/var/lib/mysql
    networks:
      space-net:
        ipv4_address: 172.28.1.4
        aliases:
          - mysql_net
          
 mysql_seeder:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-mysql-seeder
    image: 'updownio_seeder:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      space-net:
        ipv4_address: 172.28.1.5
        aliases:
          - mysql_seeder_net
    
 jobber:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-jobber
    image: updownio_jobber:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    depends_on:
      - mysql
    networks:
      space-net:
        ipv4_address: 172.28.1.6
        aliases:
          - jobber_net

networks:
  space-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
        
volumes:
  drive:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${DRIVE_PATH}
  media:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ${MEDIA_PATH}