FROM alpine:3.12

RUN mkdir /etc/periodic/30min; \
	echo '*/30    *       *       *       *       run-parts /etc/periodic/30min' >> /etc/crontabs/root; \
	apk update; \
	apk add mysql-client fping tzdata; 

COPY ping_script.sh /etc/periodic/30min/ping_script

RUN chmod +x /etc/periodic/30min/ping_script; \
	ln -s /usr/share/zoneinfo/${TZ} /etc/localtime

CMD [ "/usr/sbin/crond", "-f", "-d8" ]
